---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userbackups/finalizers
  verbs:
  - update
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userrestores/finalizers
  verbs:
  - update
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "snapshot.storage.k8s.io"
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch