# This rule is not used by the project storage-customized-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over storageresource.k8s.infracloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: storage-customized-controller
    app.kubernetes.io/managed-by: kustomize
  name: userbackup-admin-role
rules:
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userbackups
  verbs:
  - '*'
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userbackups/status
  verbs:
  - get
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userrestores
  verbs:
  - '*'
- apiGroups:
  - storageresource.k8s.infracloud
  resources:
  - userrestores/status
  verbs:
  - get  
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - "*"
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - persistentvolumeclaims
  verbs:
  - "*"


